version: '3.4'

services:
  veraboutique:
    image: ${DOCKER_REGISTRY-}veraboutique
    build:
      context: .
      dockerfile: BoutiqueMVC/Dockerfile    
    env_file:
      -  postgres.env
      -  jwt.env
      -  defaultUser.env
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro  
    depends_on:
      - "postgres"
    restart: unless-stopped

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    ports:
     - "5432:5432"
    env_file:
      -  postgres.env
    environment:
      - database-data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  database-data: