version: '3.4'

services:
  verabutik:
    image: ${DOCKER_REGISTRY-}verabutik
    build:
      context: .
      dockerfile: VeraButik/Dockerfile
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    ports:
     - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - database-data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  database-data:
  pgadmin: