version: '3.4'

services:
  verabutik:
    image: ${DOCKER_REGISTRY-}veraboutique
    build:
      context: .
      dockerfile: BoutiqueMVC/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - "postgres"

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notice
      - database-data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  database-data: